SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600

# Paddle configs
PADDLE_POSITION_LEFT = -SCREEN_WIDTH / 2 + 22
PADDLE_POSITION_RIGHT = SCREEN_WIDTH / 2 - 32

PADDLE_LIMIT_UP = 256
PADDLE_LIMIT_DOWN = -248

# Movement
DISTANCE_TO_COVER = 40
BALL_COVERS = 10

# Winning Points
WINNING_POINT = 10
