SCREEN_WIDTH = 800
SCREEN_HEIGHT = 800

# Paddle configs
PADDLE_OFFSET_LEFT = 22
PADDLE_OFFSET_RIGHT = 32

PADDLE_LIMIT_UP = 357
PADDLE_LIMIT_DOWN = -347

# Paddle position
LEFT = "left"
RIGHT = "right"
